### ISSUE TITLE
Filters module: fix prompt

### ISSUE THREAD

**Issue by bertvv** [HoGentTIN/linux-training-hogent#10]
Use consistent prompts in the code examples ( use `@linux` instead of `@debian` / `@fedora`)

**Comment by paulcobbaut** [comment]
Just for the record, since I have expressed this a long time ago already by mail.

I believe the target audience for this course is smart enough to understand that there is no such thing as @linux. Anyone managing Linux computers has to first figure out what distribution is being used. So, in my humble opinion, it does make sense to use @debian (or even @debian11 and @debian12) when a screenshot is taken on a Debian computer. Same for all other distro's of course.

I have a similar opinion about user@. The target audience will grasp that on most systems there will be user names that are not 'user'. I tend to use paul@ almost everywhere, and currently prefer tania, laura, valentina whenever I need more than one user for a screenshot. I would prefer to also see bert@ and thomas@ and dag@ (and others). This has the advantage that it is immediately clear for or us as writers (*) of these books who wrote this section.

(*) Since I am not actively contributing, and probably will not in the near future, you are of course free to ignore this. Know that it is not a deal breaker, just a minor and humble opinion.

**Comment by bertvv** [comment]
Fair points! I do try to take this into account.
In chapters about things like managing the network interfaces, or installing services, where I executed the commands on e.g. debian or almalinux, the prompt does reflect this. In those cases, the behaviour may differ on the different distributions, so it's important that the reader sees which distro behaves in which way (and if they try it themselves on another distro, they can expect different results).
In the chapter on filters, though, these commands should behave on any linux system, so for this specific chapter, I think a generic name is not unsuitable.
